title: Identificación dispersa en trayectorias de aeronaves
description: "Este proyecto trata de comprobar si el método de regresión dispersa es adecuado para obtener las ecuaciones que modelan el vuelo de una aeronave"
show_downloads: true
email: meritxell.diaz@gmail.com
author: Meritxell Díaz Coque
socials:
  GitHub: https://github.com/meridiaz
theme: jekyll-theme-architect
